// Offline vectors generated by the published upstream libraries, never Java.
import assert from "node:assert/strict";
import { mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import {
  Address, Assets, Client, COSE, EnterpriseAddress, KeyHash, PlutusV3,
  PrivateKey, ScriptHash, Transaction, TransactionHash, UTxO, VKey,
  mainnet, preprod, preview,
} from "@evolution-sdk/evolution";
import {
  buildMasumiLock, buildScriptDatumInline, buildSignedTerms, commitmentPartDigest,
  computeInputHash, computeTermsDigest, decodeCardanoTransaction,
  issueMasumiRequirements, jcs, normalizeCardanoNetwork, parseAssetUnit,
} from "@x402/cardano";
import { ExactCardanoScheme as CardanoClient } from "@x402/cardano/exact/client";
import { ExactCardanoScheme as CardanoFacilitator } from "@x402/cardano/exact/facilitator";

export const fixturePath = fileURLToPath(new URL("../src/test/resources/upstream/payments.json", import.meta.url));
const chains = { "cardano:mainnet": mainnet, "cardano:preprod": preprod, "cardano:preview": preview };
// Public BIP-39 test vector; no live chain provider or funded wallet is used.
const mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about";
const now = 1_789_992_000_000n;
const protocol = {
  minFeeA: 44, minFeeB: 155381, maxTxSize: 16384, maxValSize: 5000,
  keyDeposit: 2_000_000n, poolDeposit: 500_000_000n, drepDeposit: 500_000_000n,
  govActionDeposit: 100_000_000_000n, priceMem: 0.0577, priceStep: 0.0000721,
  maxTxExMem: 14_000_000n, maxTxExSteps: 10_000_000_000n, coinsPerUtxoByte: 4310n,
  collateralPercentage: 150, maxCollateralInputs: 3, minFeeRefScriptCostPerByte: 15,
  costModels: { PlutusV1: {}, PlutusV2: {}, PlutusV3: {} },
};
const stringify = value => JSON.stringify(value, (_, v) => typeof v === "bigint" ? v.toString() : v, 2) + "\n";
const token = `${"cd".repeat(28)}.74657374`;
const scriptCode = "4d01000033222220051200120011";

function seller(networkId) {
  const key = PrivateKey.fromBytes(Uint8Array.from({ length: 32 }, () => 51));
  const address = Address.toBech32(new EnterpriseAddress.EnterpriseAddress({
    networkId, paymentCredential: KeyHash.fromVKey(VKey.fromPrivateKey(key)),
  }));
  return {
    address,
    signTerms: (bech32, digest) => {
      const signed = COSE.SignData.signData(Address.toHex(Address.fromBech32(bech32)), Buffer.from(digest, "hex"), key);
      return { key: Buffer.from(signed.key).toString("hex"), signature: Buffer.from(signed.signature).toString("hex") };
    },
  };
}

async function buildFixture(name, network, method, asset, index) {
  const chain = chains[normalizeCardanoNetwork(network)];
  const wallet = Client.make(chain).withBlockfrost({ baseUrl: "http://127.0.0.1:1" }).withSeed({ mnemonic });
  const address = await wallet.address();
  const payer = Address.toBech32(address);
  const networkId = normalizeCardanoNetwork(network) === "cardano:mainnet" ? 1 : 0;
  const merchant = seller(networkId);
  const currentSlot = chain.slotConfig.zeroSlot + (now - chain.slotConfig.zeroTime) / BigInt(chain.slotConfig.slotLength);
  const nonce = `${index.toString(16).padStart(64, "0")}#0`;
  const amount = asset === "lovelace" ? "3000000" : "7";
  let requirements = { scheme: "exact", network, asset, amount, payTo: merchant.address, maxTimeoutSeconds: 600,
    extra: { assetTransferMethod: method, areFeesSponsored: false, confirmationPolicy: { l1Confirmations: 1 } } };
  if (method === "masumi") {
    requirements = await issueMasumiRequirements({
      network, asset, amount, maxTimeoutSeconds: 600, sellerAddress: merchant.address, signTerms: merchant.signTerms,
      commitment: [{ name: "body", canonicalization: "jcs", content: { units: "metric", days: 3 } }],
      sellerNonce: index.toString(16).padStart(64, "0"), buyerNonce: "",
      payByTime: (now + 600_000n).toString(), submitResultTime: (now + 1_800_000n).toString(),
      unlockTime: (now + 2_700_000n).toString(), externalDisputeUnlockTime: (now + 3_600_000n).toString(),
      confirmationPolicy: { l1Confirmations: 1 }, unsafeSkipPolicyChecks: true,
    });
  } else if (method === "script") {
    const scriptHash = ScriptHash.fromScript(new PlutusV3.PlutusV3({ bytes: Buffer.from(scriptCode, "hex") }));
    requirements.payTo = Address.toBech32(new EnterpriseAddress.EnterpriseAddress({ networkId, paymentCredential: scriptHash }));
    requirements.extra = { ...requirements.extra, script: { type: "plutusV3", code: scriptCode }, datum: "d87980" };
  }
  const inputCoin = 30_000_000n;
  const nativeAssets = asset === "lovelace" ? {} : { [asset]: BigInt(amount) };
  let inputAssets = Assets.fromLovelace(inputCoin);
  if (asset !== "lovelace") {
    const { policyId, assetNameHex } = parseAssetUnit(asset);
    inputAssets = Assets.addByHex(inputAssets, policyId, assetNameHex, BigInt(amount));
  }
  const input = new UTxO.UTxO({ transactionId: TransactionHash.fromHex(nonce.split("#")[0]), index: 0n,
    address, assets: inputAssets, datumOption: undefined, scriptRef: undefined });
  let datum;
  let outputCoin = asset === "lovelace" ? BigInt(amount) : 2_000_000n;
  if (method === "masumi") {
    const lock = buildMasumiLock(requirements.extra, payer, asset, BigInt(amount), 4310n);
    datum = lock.datum;
    outputCoin = lock.lockedLovelace;
  } else if (method === "script") {
    datum = buildScriptDatumInline(requirements.extra);
  }
  let outputAssets = Assets.fromLovelace(outputCoin);
  if (asset !== "lovelace") {
    const { policyId, assetNameHex } = parseAssetUnit(asset);
    outputAssets = Assets.addByHex(outputAssets, policyId, assetNameHex, BigInt(amount));
  }
  const client = new CardanoClient({
    getAddress: () => payer,
    buildAndSignPaymentTransaction: async () => {
      const builder = await wallet.newTx().collectFrom({ inputs: [input] })
        .payToAddress({ address: Address.fromBech32(requirements.payTo), assets: outputAssets, ...(datum ? { datum } : {}) })
        .setValidity({ to: now + 300_000n })
        .build({ availableUtxos: [input], changeAddress: address, fullProtocolParameters: protocol, autoMinUtxo: false });
      const signed = await builder.sign();
      const unsigned = await builder.toTransaction();
      const transaction = new Transaction.Transaction({ body: unsigned.body, witnessSet: signed.witnessSet, isValid: true, auxiliaryData: null });
      return { transaction: Buffer.from(Transaction.toCBORBytes(transaction)).toString("base64"), nonce };
    },
  });
  const result = await client.createPaymentPayload(2, requirements);
  const payload = { ...result, accepted: requirements, resource: { url: `https://interop.invalid/${name}` } };
  const decoded = decodeCardanoTransaction(payload.payload.transaction);
  const snapshot = { exists: true, address: payer, coin: inputCoin, assets: nativeAssets };
  const reference = new CardanoFacilitator({
    getAddresses: () => [], getCurrentSlot: async () => currentSlot, getUtxo: async () => snapshot,
    getProtocolParameters: async () => ({ coinsPerUtxoByte: 4310n, minFeeCoefficient: 44n, minFeeConstant: 155381n }),
    getTransactionEvidence: async () => ({ status: "unknown", confirmations: -2 }),
    submitTransaction: async () => { throw new Error("offline fixtures must never submit"); },
  });
  const verified = await reference.verify(payload, requirements);
  assert.equal(verified.isValid, true, `${name}: ${JSON.stringify(verified)}`);
  return { name, currentSlot, requirements, payload, payer, txHash: decoded.txHash, inputs: { [nonce]: snapshot },
    ...(method === "masumi" ? { signedTerms: buildSignedTerms(requirements.extra, requirements),
      termsDigest: computeTermsDigest(buildSignedTerms(requirements.extra, requirements)),
      inputHash: computeInputHash(requirements.extra.inputCommitment) } : {}) };
}

export async function generateFixtures() {
  const scenarios = [
    ["ada", "cardano:preprod", "default", "lovelace"],
    ["token", "cardano:preprod", "default", token],
    ["script", "cardano:preprod", "script", "lovelace"],
    ["masumi-ada", "cardano:preprod", "masumi", "lovelace"],
    ["masumi-token", "cardano:preprod", "masumi", token],
    ["mainnet-offline", "cardano:mainnet", "default", "lovelace"],
    ["preview-offline", "cardano:preview", "default", "lovelace"],
    ["preprod-alias", "cip34:0-1", "default", "lovelace"],
  ];
  const payments = [];
  for (const [index, args] of scenarios.entries()) payments.push(await buildFixture(...args, index + 1));
  const invalidPayments = [];
  const mutations = [
    ["leading-zero-amount", "ada", p => { p.requirements.amount = "03000000"; }],
    ["uppercase-asset", "token", p => { p.requirements.asset = p.requirements.asset.toUpperCase(); }],
    ["null-confirmation-policy", "ada", p => { p.requirements.extra.confirmationPolicy = null; }],
    ["closed-confirmation-policy", "ada", p => { p.requirements.extra.confirmationPolicy.settlementLayer = "l1"; }],
    ["missing-masumi-identifier", "masumi-ada", p => { delete p.requirements.extra.blockchainIdentifier; }],
    ["removed-masumi-submission-policy", "masumi-ada", p => { p.requirements.extra.submissionPolicy = "server"; }],
    ["changed-masumi-commitment", "masumi-ada", p => { p.requirements.extra.inputCommitment.parts[0].content.days = 4; }],
    ["surrogate-masumi-content", "masumi-ada", p => { p.requirements.extra.inputCommitment.parts[0].content.note = "\ud800"; }],
    ["surrogate-masumi-part-name", "masumi-ada", p => { p.requirements.extra.inputCommitment.parts[0].name = "\ud800"; }],
    ["surrogate-masumi-media-type", "masumi-ada", p => { p.requirements.extra.inputCommitment.parts[0].mediaType = "\udc00"; }],
  ];
  for (const [name, source, mutate] of mutations) {
    const p = structuredClone(payments.find(p => p.name === source));
    mutate(p);
    p.payload.accepted = p.requirements;
    const reference = new CardanoFacilitator({
      getAddresses: () => [], getCurrentSlot: async () => p.currentSlot,
      getUtxo: async () => Object.values(p.inputs)[0],
      getProtocolParameters: async () => ({ coinsPerUtxoByte: 4310n, minFeeCoefficient: 44n, minFeeConstant: 155381n }),
      getTransactionEvidence: async () => ({ status: "unknown", confirmations: -2 }),
      submitTransaction: async () => { throw new Error("offline fixtures must never submit"); },
    });
    const expected = await reference.verify(p.payload, p.requirements);
    assert.equal(expected.isValid, false, `${name} must be rejected by upstream`);
    invalidPayments.push({ name, payload: p.payload, requirements: p.requirements, expected });
  }
  const contents = [null, { z: 1e30, a: 0.000001, b: 0.0000001 }, { "€": "😀", "a": "\n", "é": true }, { nested: [null, true, "", -0, 1.25] }];
  const vectors = { upstreamCommit: "6323ec74c85607e706e0722dd294365a7fb57768", cardanoVersion: "2.26.0",
    clockMillis: now, payments, invalidPayments,
    jcs: contents.map(content => ({ content, canonical: jcs(content), digest: commitmentPartDigest({ canonicalization: "jcs", content }) })) };
  await mkdir(new URL("../src/test/resources/upstream/", import.meta.url), { recursive: true });
  await writeFile(fixturePath, stringify(vectors));
  console.log(`Generated ${payments.length} valid and ${invalidPayments.length} invalid payment fixtures; all checked by @x402/cardano 2.26.0`);
  return vectors;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) await generateFixtures();
